[general]
import = [
#  "~/.config/alacritty/themes/themes/one_dark.toml"
  "~/.config/alacritty/custom_onedark.toml"
]
live_config_reload = true

[window]
blur = true
opacity = 0.9
padding = {x = 8, y = 4}
dynamic_padding = true

[font]
size = 10

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[cursor.style]
shape = "Block"
